config/routes.rb
Nearbuy::Application.routes.draw do

  root "static_pages#index"
  get "/about" => "static_pages#about"
  get "/logout" => "sessions#destroy", as: :logout

  get "/update_geolocation" => "addresses#update_geolocation", as: :update_geolocation

  resources :users
  resources :profiles, only: [:update, :edit]
  resources :addresses
  resources :sessions, only: [:create, :new, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :communities

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :items do
    collection do
      get "search"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  # Here is where profile information should be stored
  has_one :profile, dependent: :destroy, inverse_of: :user

  accepts_nested_attributes_for :profile

  has_one :image, as: :imageable, dependent: :destroy # Profile picture
  accepts_nested_attributes_for :image, allow_destroy: true

  has_many :items, dependent: :destroy
  has_many :comments, through: :items

  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: lambda{|address| address[:number_and_street].blank? }


  # A user's communities
  has_many :community_members, -> { uniq }
  has_many :communities, -> { uniq }, through: :community_members

  # Communities a user moderates
  has_many :community_moderators, -> { uniq }
  has_many :moderating_communities, -> { uniq }, through: :community_moderators, source: :community

  has_many :admin_communities, class_name: "Community", foreign_key: "owner_id"



  before_create :make_profile


  validates :email,
    presence: true,
    uniqueness: true,
    format:{with:EMAIL_REGEX, multiline:true}

  validates :password,
    presence:true, on: :create,
    confirmation:true

  # Make sure a profile is associated with the user upon creation
  def make_profile
    self.profile = Profile.new if self.profile.nil?
  end

  #def first_name=(value)
  #  write_attribute :first_name, value.capitalize
  #end

  #def last_name=(value)
  #  write_attribute :last_name, value.capitalize
  #end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only:[:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @address = Address.new #current_user.addresses.build
  end

  def new
    @user = User.new
  end

  def edit
    authorize! :update, @user
    @user.build_image if @user.image.nil?
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save 
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @user
    respond_to do |format|
      if @user.update(user_profile_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end 
  end

  def destroy
    authorize! :destroy, @user
  end


  private
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end 
  
    def user_profile_params
      params.require(:user).permit(:first_name, :last_name, addresses_attributes:[:name, :number_and_street, :city, :zip_code, :country_id, :_destroy], image_attributes:[:url])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_fields.haml
%em Address
= address.link_to_remove "Remove this Address"
.field
  = address.label :name 
  = address.text_field :name 
.field
  = address.label :number_and_street 
  = address.text_field :number_and_street 
.field
  = address.label :city
  = address.text_field :city
.field
  = address.label :zip_code
  = address.text_field :zip_code
.field
  = address.label :country_id
  = address.collection_select(:country_id, Country.all, :id, :name)

app/views/users/_form.haml
= nested_form_for @user, html_option:{multipart:true} do |f|
  %fieldset
    %legend Personal Information
    .fields
      = f.label :first_name
      = f.text_field :first_name
    .fields
      = f.label :last_name
      = f.text_field :last_name

  %fieldset
    %legend Image
    = f.fields_for :image do |form|
      = image_tag @user.image.url, id: "profile_picture" unless @user.image.id.nil?
      = form.label :url, "Profile Picture"
      = form.file_field :url

  /%fieldset
  /  %legend Contact Information
  /  = f.fields_for :addresses do |address|
  /    = render partial:"address_fields", locals:{address: address}
  /  = f.link_to_add "Add an Address", :addresses

  = f.submit

app/views/users/edit.haml
.row
  .col-lg-12
    %h1 Edit your profile

    = render partial:"form"

app/views/users/new.haml
.row
  %h1 Sign Up
  = form_for @user, html:{class:"form-horizontal", role: "form"} do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message
    .form-group
      = f.label :email, nil, class:"col-lg-2 control-label col-lg-offset-3"
      .col-lg-4
        = f.text_field :email, class:"form-control", placeholder: "Email"
    .form-group
      = f.label :password, nil, class:"col-lg-2 control-label col-lg-offset-3"
      .col-lg-4
        = f.password_field :password, class: "form-control", placeholder: "Password"
    .form-group
      = f.label :password_confirmation, "Password Confirmation", class:"col-lg-2 control-label col-lg-offset-3"
      .col-lg-4
        = f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"
    .actions 
      .col-lg-4.col-lg-offset-5
        = f.submit "Signup", class: "btn btn-success form-control"

app/views/users/show.haml
.row
  .col-lg-6
    %h1= "Profile of #{@user.email}"
.row
  .col-lg-6.col-lg-offset-6{style: "text-align: right"}
    = link_to "Edit profile", edit_profile_path(@user.profile), class: "btn btn-info" if can? :update, @user.profile

.row
  .col-lg-12
    = image_tag @user.image.url if @user.image

    %h4 Contact information
    First Name 
    \:
    = @user.profile.first_name || "No first name"
    %br
    Last Name 
    \:
    = @user.profile.last_name || "No last name"

    %hr.soften

.row
  .col-lg-12
    %h4 Preferences
    Units: 
    = distance_units

    %hr.soften
- if @user == current_user
  .row
    .col-lg-6
      %h4 Addresses

  .row
    .col-lg-6
      - current_user.addresses.includes(:country).each do |address|
        .row
          .col-lg-6
            %address
              %strong= address.name
              %br
              =address.number_and_street
              %br
              = address.city
              %br
              = "#{address.state} #{address.zip_code}, #{address.country.name}"
          .col-lg-6
            = link_to "Edit", edit_address_path(address) if can? :edit, address
            \|
            = link_to "Delete", address_path(address), method: :delete, data: { confirm: 'Confirm please?' }
      /= render partial:"addresses/form"
      = link_to "Add Address", new_address_path, class: "btn btn-success"


    .col-lg-6
      = render partial:"layouts/map", locals:{places: @user.addresses} if @user == current_user

app/views/users/update.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml