config/routes.rb
Nearbuy::Application.routes.draw do

  root "static_pages#index"
  get "/about" => "static_pages#about"
  get "/logout" => "sessions#destroy", as: :logout

  get "/update_geolocation" => "addresses#update_geolocation", as: :update_geolocation

  resources :users
  resources :profiles, only: [:update, :edit]
  resources :addresses
  resources :sessions, only: [:create, :new, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :communities

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :items do
    collection do
      get "search"
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true, reject_if: lambda{|address| address[:number_and_street].blank? }

  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: lambda{|x| x[:url].blank?}

  has_many :categorizations
  has_many :categories, through: :categorizations

  has_many :comments, as: :commentable, dependent: :destroy

  validates :name,
    presence: true

  validates :address_id,
    presence: true

  validates :categories,
    length:{ minimum: 1, message: "item needs at least one category"}


  def name=(value)
    write_attribute :name, value.capitalize
  end


  #searchable do
  #  text :name, boost: 10
  #  text :description, boost: 7
  #  integer :address_id
  #  integer :category_ids, multiple: true do
  #    categories.map { |x| x.id }
  #  end

  #end

  def self.item_search(query, address=nil, range=10, categories=nil)
    categories ||= Category.pluck(:id)
    #self.search do
    #  fulltext query
    #  with(:address_id, Address.near(address, range).map{|x| x.id})
    #  with(:category_ids, categories)
    #end
    Item.joins(:categories).where("categories.id" => categories, address_id: Address.near(address, range).map{|x| x.id}.to_a).group("items.id").where("items.name @@ :q OR items.description @@ :q", q: "%#{query}%").order("items.id DESC")
  end

  # Find items in a certain radius of a location
  def self.near(address=nil, range=RANGE_CONSTANT, categories=nil)
    categories ||= Category.pluck(:id)
    Item.joins(:categories).where("categories.id" => categories, address_id: Address.near(address, range).map{|x| x.id}.to_a).group("items.id").order("items.id DESC")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :find_address, only:[:search, :show]

  skip_before_action :require_login, only:[:show, :search]

  def index
    @addresses = current_user.addresses.map{|address| address unless address.items.empty?}.compact
    @items = current_user.items
  end

  def show
  end

  def new
    @item = current_user.items.build
    @addres = @item.build_address
  end

  def edit
    authorize! :update, @item
  end

  def create
    if params[:item][:address_id]
      @item = current_user.items.build(item_params)
    else
      @item = current_user.items.build(item_with_address_params)
      current_user.addresses << @item.address if (@item.address && @item.address.valid?)
      @item.address = @item.address
    end
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html {
          @addres = @item.build_address

          render action: 'new'
        }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @item
    @item.destroy
    redirect_to items_path
  end

  def search
    # @address already set by find_address
    @categories = params[:categories].split(",") unless params[:categories].nil?
    @query = params[:query]
    @range = params[:range] ? params[:range].to_f : RANGE_CONSTANT
    @range = @range * current_user.profile.distance_multiplier if current_user
    @items = (params[:query] && !params[:query].blank?) ? Item.item_search(@query, @address, @range, @categories).includes(:user, :address, :images) : Item.near(@address, @range, @categories).includes(:user, :address, :images)
    @items = @items.sample(4) unless current_user
    respond_to do |format|
      format.html{
        render template: "static_pages/index"
      }
      format.json{
        render json: @items.map{|item| {id: item.id, name: item.name, description: item.description, image: item.images.empty? ? nil : item.images.first.url }}
        }
      format.js{

        render layout: false

      }
    end
  end

  private
    def find_address
      @address = params[:address] && !params[:address][:latitude].blank? ? Address.new(address_params) : user_current_location
    end

    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :address_id, images_attributes:[:url], :category_ids => [])
    end
    def item_with_address_params
      params.require(:item).permit(:name, :description, :address_id, images_attributes:[:url], address_attributes:[:name, :number_and_street, :city, :zip_code, :country_id, :state], :category_ids => [])
    end
    def address_params
      params.require(:address).permit(:latitude, :longitude)
    end

    def address_params
      params.require(:address).permit(:latitude, :longitude)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.haml
.row
  .col-lg-12
    = nested_form_for @item, namespace: "standard", html:{class:"form-horizontal", role:"form"} do |f|
      .row
        - if @item.errors.any?
          .error_messages
            %h2 Form is invalid
            %ul
              - for message in @item.errors.full_messages
                %li= message

      .row
        .col-lg-6.col-lg-offset-3
          %legend Item Info
      .row
        .col-lg-12

          .field.form-group
            = f.label :name, nil, class:"col-lg-2 control-label col-lg-offset-3"
            .col-lg-4
              = f.text_field :name, class:"form-control", placeholder: "Name"

          .field.form-group
            = f.label :description, nil, class:"col-lg-2 control-label col-lg-offset-3"
            .col-lg-4
              = f.text_area :description, class:"form-control", placeholder: "Description"

          .field.form-group
            %legend.col-lg-6.col-lg-offset-3 Address
            #form_old_address{style:("display: none" if current_user.addresses.empty?)}
              = f.label :address_id, nil, class:"col-lg-2 control-label col-lg-offset-3"
              .col-lg-4#old_address
                = f.select :address_id, options_for_select(current_user.addresses.map{|x| [x.name, x.id]}), {}, class: "form-control"
                = link_to "New Address", "#", id: "new_address"

            #form_new_address{style:("display: none" unless current_user.addresses.empty?)}

              = f.fields_for :address do |address_form|
                .field.form-group
                  = address_form.label :name, nil, class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.text_field :name, placeholder: "Home", class:"form-control"
                .field.form-group
                  = address_form.label :number_and_street, "Number And Street",  class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.text_field :number_and_street, class:"form-control"

                .field.form-group
                  = address_form.label :city, nil,  class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.text_field :city, class: "form-control"

                .field.form-group
                  = address_form.label :state, nil,  class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.select :state, ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"], {}, class:"form-control"

                .field.form-group
                  = address_form.label :zip_code, class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.text_field :zip_code, class: "form-control"
                
                .field.form-group
                  = address_form.label :country_id, class: "col-lg-2 control-label col-lg-offset-3"
                  .col-lg-4
                    = address_form.collection_select(:country_id, Country.all, :id, :name, {}, {class: "form-control"})
  


          .field.form-group
            .col-lg-6.col-lg-offset-3
              %legend Categories
              - Category.all.each do |category|
                = check_box_tag "item[category_ids][]", category.id, @item.category_ids.include?(category.id)
                = category.name

        .col-lg-6.col-lg-offset-3
          %legend Pictures
          .item_picture_list
            - @item.images.each do |image|
              = image_tag image.url, class: "item_tile"

          .field.form-group
            = f.fields_for :images do |form|
              = f.label :url, "Add Picture", class:"col-lg-3 control-label"
              .col-lg-7
                = form.file_field :url, class:"form-control"
            = f.link_to_add "Add an image", :images

          .actions
            .col-lg-4.col-lg-offset-5
              = f.submit "Submit", class: "btn btn-success"

app/views/items/_items.haml
.items#items.js-masonry{"data-masonry-options"=>'{ "itemSelector": ".item" }'}
  - items.each do |item|
    .item{style:"border-top: 5px solid #{cycle("red","green","blue", "black", "orange")}"} 
      %h1= link_to item.name, item_path(item)
      = link_to image_tag(item.images.first.url) , item_path(item) unless item.images.empty? 
      %p.description
        = truncate(item.description, length: 100)
      %p.distance  
        = "<"
        = distance_calculator(item.address, @address)
        = distance_units
      %p.posted_by
        Posted 
        - days = ((Time.zone.now - item.created_at) / (24*3600)).floor
        = days == 0 ? "today" : pluralize(days, "day ago", "days ago")
        by
        = link_to item.user.profile.first_name || "No Name Given", user_path(item.user)

:coffee
  jQuery ->
    $("#items").masonry(
      {
        itemSelector: '.item'
      }
    )
    imgs = $("#items img")
    for img in imgs
      $(img).load(
        () ->
          $("#items").masonry(
            {
              itemSelector: '.item'
            }
          )
      )

app/views/items/edit.haml
.row
  .col-lg-12
    = render partial: "form"

app/views/items/index.haml
.row.container
  .col-lg-12
    %h1 Items you have listed

- if @addresses.empty?
  .row.container
    .col-lg-6
      You have no items yet. 
      = link_to "start listing items now", new_item_path
.row.container
  .col-lg-4.col-lg-offset-2.col-xs-4.col-xs-offset-2
  = link_to "New Item", new_item_path, class: "btn btn-success"

.row.container
  .col-lg-12
    - @addresses.each do |address|
      %strong= address.name
      - address.items.each do |item|
        .row.container
          .col-lg-2.col-xs-2
            = item.name
          .col-lg-2.col-xs-2
            = link_to "View", item_path(item.id), class: "btn btn-primary"
          .col-lg-2.col-xs-2
            = link_to "Edit", edit_item_path(item.id), class: "btn btn-warning"
          .col-lg-2.col-xs-2
            = link_to "Delete", item_path(item.id), method: :delete, class: "btn btn-danger"

app/views/items/new.haml
.row
  .col-lg-12
    %h1 New Item
    = render partial: "form"

app/views/items/show.haml
.row
  .col-lg-12
    %h1 
      Item #{@item.name}
      = link_to "Edit", edit_item_path(@item), class:"btn btn-warning" if can? :edit, @item

.row
  .col-lg-6
    .row
      .col-lg-6
        %h2 Name
        = @item.name
      .col-lg-6
        %h3 Location
        = distance_calculator(@item.address, @address)
        = distance_units 
        from you
    %h3 Description
    = @item.description
    %hr.soften
    %h4 Categories
    - @item.categories.each do |category|
      = @item.categories.map{|c| c.name}.join(", ")

    %br
    - @item.images.each do |image|
      = image_tag image.url

  .col-lg-6
    = render partial:"layouts/map", locals:{places: [@item.address]}


.row
  .col-lg-6.col-lg-offset-3
    %h3 Comments
    = render partial: "comments/form", locals:{comment: @item.comments.build} if current_user
    %br
    = render partial: "comments/comments", locals:{comments: @item.comments}