config/routes.rb
Nearbuy::Application.routes.draw do

  root "static_pages#index"
  get "/about" => "static_pages#about"
  get "/logout" => "sessions#destroy", as: :logout

  get "/update_geolocation" => "addresses#update_geolocation", as: :update_geolocation

  resources :users
  resources :profiles, only: [:update, :edit]
  resources :addresses
  resources :sessions, only: [:create, :new, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :communities

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :items do
    collection do
      get "search"
    end
  end

end

app/views/layouts/_map.haml
.gmap
  = gmaps("map_options" => {"libraries" => ["places"], "zoom" => 10, "auto_zoom" => places.length > 1, id: "map_#{places.first.id}"}, "markers" => {"data" => places.to_gmaps4rails}) if !places.first.nil?

app/views/layouts/_nav.haml
.row
  %nav.navbar.navbar-inverse{role: "navigation", style:"margin-bottom: 0px"} 
    .container
      .navbar-header
        %button.navbar-toggle{type:"button", "data-toggle" => "collapse", "data-target" => ".navbar-ex1-collapse"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Nearbuy", root_path, class:"navbar-brand"
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
          - if current_user
            %li= link_to "My Profile", user_path(current_user)
            %li= link_to "My Items", items_path
            %li= link_to "My Communities", communities_path

        %ul.nav.navbar-nav.navbar-right
          %li= link_to "About", about_path
          - if current_user
            /%li= link_to "Logout #{current_user.email}", logout_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                = current_user.email 
                %b.caret
              %ul.dropdown-menu.clearfix{role: "menu", "aria-labelledby"=>"brow", style:"z-index: 2000"}
                %li= link_to "Logout", logout_path
                %li= link_to "Preferences", "#"
              
            
            
          - else 
            %li= link_to "Login", "#login_modal", "data-toggle"=>"modal"


  %nav.navbar#search_navbar{role: "navigation"} 
    .container
      .col-lg-4
        - if current_user
          %form.navbar.navbar-form
            = text_field_tag "OK", nil, placeholder: "Spread Post", class:"form-control", id:"post_item"
          = form_for @form_item, html:{class:"navbar-form form-inline"} do  |f|
            .dropdown#spread_post_d
              .dropdown-menu#spread_post_dropdown{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
                .close_drop_down.pull-right{style: "font-size: 26px; display: block"}= link_to "×", "#"
                %br
                .field
                  .row
                    .col-lg-10
                      = f.label :name, nil, class:"label-control"
                    .col-lg-2
                  = f.text_field :name, class: "form-control", placeholder: "Spread Post"

                .field
                  = f.label :description, nil, class:"label-control"
                  = f.text_area :description, class: "form-control"
                .field
                  = f.label :categories, "Categories"
                  %br
                  - Category.all.each do |category|
                    = check_box_tag "item[category_ids][]", category.id, @form_item.category_ids.include?(category.id)
                    = category.name
                  

                #new_address_form{style:("display: none" unless current_user.addresses.empty?)}
                  = f.fields_for :address, id:"old_address" do |address_form|
                    .field
                      = address_form.label :name, "Address Name", class: "control-label"
                      = address_form.text_field :name, placeholder: "Address Name", class:"form-control"
                    .field
                      = address_form.label :number_and_street, "Number And Street",  class: "control-label"
                      = address_form.text_field :number_and_street, class:"form-control"
                    .field
                      = address_form.label :city, nil,  class: "control-label"
                      = address_form.text_field :city, class: "form-control"
                    
                    .field
                      = address_form.label :state, nil,  class: "control-label"
                      = address_form.select :state, ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"], {}, class:"form-control"
                    .field
                      = address_form.label :zip_code, class: "control-label"
                      = address_form.text_field :zip_code, class: "form-control"
                    
                    .field
                      = address_form.label :country_id, class: "control-label"
                      = address_form.collection_select(:country_id, Country.all, :id, :name, {}, {class: "form-control"})
                        
                #old_address_form{style:("display: none" if current_user.addresses.empty?)}
                
                  .field
                    = f.label :address_id, nil, class:"control-label"
                    = f.select :address_id, options_for_select(current_user.addresses.map{|x| [x.name, x.id]}), {}, class: "form-control"
                    .pull-right
                      = link_to "New Address", "#", id: "new_address"
                .field
                  = f.fields_for :images do |form|
                    = form.label :url, "Add Picture", class:"label-control"
                    = form.file_field :url, class:"form-control"
                .field 
                  %br
                  = f.submit class: "btn btn-warning col-lg-12"

      .col-lg-8
        .row
          = form_tag search_items_path, method: :get, class:"navbar-form form-inline", id: "search_address", role: "search" do
            #query_nav.col-lg-6.col-lg-offset-1
              = label_tag :query, nil, class:"sr-only"
              = text_field_tag :query, nil, placeholder:"What? (Hammer, Ladder, ...)", class: "form-control", value:"#{params[:query]}"
               
            #location_query_nav.col-lg-3
              = label_tag :location, nil, class:"sr-only"
              = text_field_tag :location, nil, placeholder:"Where? (San Francisco, Brisbane, ...)", class: "form-control", id:"search_location_nav", value:"#{params[:location]}"
              %input{type:"hidden", id:"address[latitude]", name:"address[latitude]"} 
              %input{type:"hidden", id:"address[longitude]", name:"address[longitude]"}
              %input{type:"hidden", id:"search_range", name:"range", value:"#{params[:range] ? params[:range] : RANGE_CONSTANT}"}
            .col-lg-2
              = submit_tag "Go", class: "form-control btn btn-warning"

.row
  - if !current_user
    #login_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}/
    = render partial:"sessions/login"

app/views/layouts/application.haml
!!!
%html
  %head
    %title Nearbuy
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield :head
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %body
    = render partial:"layouts/nav"
    .container
      .row
        .col-lg-12
          - unless flash[:notice].blank?
            .alert.alert-info.alert-dismissable
              %button{type:"button", class:"close", "data-dismiss" => "alert", "aria-hidden" => "true"} &times;
              = flash[:notice]
          - unless flash[:alert].blank?
            .alert.alert-danger.alert-dismissable 
              %button{type:"button", class:"close", "data-dismiss" => "alert", "aria-hidden" => "true"} &times;
              = flash[:alert] 

      .row
        .col-lg-12
          #map_banner
      .row
        = yield

    %hr.soften
    .row.footer
      .container
        %footer
          .col-lg-6.col-sm-6.col-xs-6
            &copy; 2013 - Nearbuy
          .col-lg-6.col-sm-6.col-xs-6
            .pull-right
              :plain
                <a href="mailto:&#119;&#097;&#104;&#108;&#055;&#055;+web&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;">
                  Contact
                </a>                                         

    - if content_for?(:scripts)
      = yield :scripts
    - else 
      %script{type:"text/javascript", src:"http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"}


    - unless cookies[:position]
      :coffee
        jQuery -> 
          # Get user location
          find_user_geolocation()